## NumPy Practice Questions

In [2]:
import numpy as np

1. Array Creation: Create a NumPy array of integers from 1 to 10

In [6]:
arr1=np.arange(11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


2. Array Operations: Perform element-wise addition, subtraction, multiplication, and
division on two NumPy arrays.

In [13]:
arr2=np.array([2,4,6,8])
arr3=np.array([1,3,5,7])

#Element-wise addition
arr_add= arr2+arr3
print(arr_add)

#Element wise subtraction
arr_sub= arr2-arr3
print(arr_sub)

#Element-wise multiplication
arr_multi=arr2*arr3
print(arr_multi)

#Element-wise division
arr_div=arr2/arr3
print(arr_div)


[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]


3. Array Slicing: Extract the first three elements from a NumPy array.

In [14]:
print(arr_multi[0:3])

[ 2 12 30]


4. Array Reshaping: Reshape a 1D NumPy array into a 2D array with 2 rows and 3
columns.

In [17]:
arr4=np.arange(6).reshape(2,3)
print(arr4)

[[0 1 2]
 [3 4 5]]


5. Array Aggregation: Calculate the mean, median, and standard deviation of a NumPy
array

In [27]:
arr5=np.mean(arr1)
print('Mean value: ',arr5)

arr5=np.median(arr1)
print('Median value: ',arr5)

arr5=np.std(arr1)
print('Standard deviation: ',arr5)


Mean value:  5.0
Median value:  5.0
Standard deviation:  3.1622776601683795


## Pandas Practice Questions

In [28]:
import pandas as pd

1. DataFrame Creation: Create a pandas DataFrame from a dictionary of lists, where
each list represents a column.

In [30]:
#Dictionary of Lists 
data= { 'Name': ['Sam','Alice','Sophie'], 'Age': [19, 22, 27], 'Level': [5,2,1]}
df1=pd.DataFrame(data)
print(df1)

     Name  Age  Level
0     Sam   19      5
1   Alice   22      2
2  Sophie   27      1


2. DataFrame Operations: Add a new column to an existing DataFrame. Perform
element-wise operations between two columns.

In [38]:
#Adding column Gender to the DataFrame
df1['Gender']=['Female', 'Female', 'Female']
print(df1)

#Element-wise operations between two columns
df1['AgeLevel Product']=df1['Age']*df1['Level']
print(df1)

     Name  Age  Level  Gender
0     Sam   19      5  Female
1   Alice   22      2  Female
2  Sophie   27      1  Female
     Name  Age  Level  Gender  AgeLevel Product
0     Sam   19      5  Female                95
1   Alice   22      2  Female                44
2  Sophie   27      1  Female                27


3. Data Selection: Select rows based on a condition. Select specific columns from a
DataFrame

In [40]:
#select rows based on a condition
df1_filterAge=df1[df1['Age']>20]
print(df1_filterAge)

#select specific column from DataFrame
gender=df1['Gender']
print(gender)

     Name  Age  Level  Gender  AgeLevel Product
1   Alice   22      2  Female                44
2  Sophie   27      1  Female                27
0    Female
1    Female
2    Female
Name: Gender, dtype: object


4. Data Aggregation: Group the data in a DataFrame based on a categorical column and
calculate the mean of each group.

In [42]:
#Group by a specific column
groupAge= df1.groupby('Age')
print(groupAge)

#Calculated mean of column
mean_age=groupAge['Age'].mean()
print(mean_age)

Age
19    19.0
22    22.0
27    27.0
Name: Age, dtype: float64


5. Data Cleaning: Handle missing values by either removing or replacing them with
appropriate values.

In [43]:
# Drop missing values
df1_cleaned = df1.dropna()

# Fill missing values
df1_filled = df1.fillna(0)

# Check for missing values
print(df1.isnull().any())


Name                False
Age                 False
Level               False
Gender              False
AgeLevel Product    False
dtype: bool


## Technical Level Questions and Exercises

In [45]:
###Implementing Matrix Operations: Matrix Multiplication

import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [48]:
## Question: Multiply matrices A and B (linear algebra)

# Answer
C=np.dot(A,B)
print(C)

[[19 22]
 [43 50]]


In [50]:
## Question: Matrix Inversion - Find the inverse of matrix A.

# Answer
inverseA= np.linalg.inv(A)
print(inverseA)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [52]:
## Question: Calculate the eigenvalues and eigenvectors of matrix A.

# Answer
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues) 
print()
print(eigenvectors) 

[-0.37228132  5.37228132]

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [54]:
## Question: Solve the system of equations 3x + y = 9 and x + 2y = 8.

# Solving a system of linear equations
A = np.array([[3, 1], [1, 2]])  #left hand side 
b = np.array([9, 8])            #right hand side
x = np.linalg.solve(A, b)


# Answer
x = np.linalg.solve(A, b)
print(x) # Output: [2. 3.]

[2. 3.]


In [55]:
import numpy as np

# Define the 2D array
arr15 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Array:")
print(arr15)

#Define row and column indices
#reads as row 1 column 0 and row 2 column 1
row_indices = np.array([1, 2])
column_indices = np.array([0, 1])

# Use a tuple for fancy indexing
selected_elements = arr15[(row_indices, column_indices)]

print("\nSelected Elements:")
print(selected_elements)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Selected Elements:
[4 8]
